### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by DJPatron** [talabadi/KASPA-mine-rate-calculator#1]
ubuntu@instance-sws-micro1:~/KASPA-mine-rate-calculator$ python3 kas-rate-source.py
Traceback (most recent call last):
  File "kas-rate-source.py", line 7, in <module>
    locale.setlocale(locale.LC_ALL, 'en_US')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by talabadi** [comment]
First, you need to install locales package :
`sudo apt-get install locales -y`

Then use the locale-gen command to generate locales :
`sudo locale-gen en_US`

See [https://linuxpip.org/fix-python-locale-error/](url) for more information.
